### PR TITLE
Ignore 0-length messages.

### PR DESCRIPTION
**Pull request by derekelkins**

### CODE REVIEW

**Comment by edenhill** [comment]
Sorry for the delay.

I think the most honest and generic approach is to output empty messages by default with all delimiters in place, but to provide an option to ignore empty messages (-Z).

What do you think?

**Comment by derekelkins** [comment]
Despite my initial pull request, my feeling is removing the empty messages is rarely desirable.  They almost certainly occur only rarely and the tool should try to present what it receives as faithfully as possible.  In interactive usage, it's easy enough to write a sed script to remove empty lines, and that gives the flexibility of removing lines containing only whitespace if that's desired as well.  In unattended scenarios, the downstream processing can easily filter out empty messages if that is necessary and desired.

My opinion is a -Z option would be a waste of effort.  For me, the important thing was not to have kafkacat crash on legitimate, if unusual, input.

**Comment by edenhill** [comment]
Okay, fair enough!

Just to clarify, did you actually see kafkacat crashing or misbehaving on empty messages?

**Comment by derekelkins** [comment]
Oh, not as in segfaulting, just as in hitting that fatal error message.

**Comment by edenhill** [comment]
This is fixed in the json_support branch.

**Pull request closed without merging**
