### PR TITLE
change default timeout 5s to 30s to accomodate slower but working setups

### PR DESCRIPTION
**Pull request by SSSSeb**

### CODE REVIEW

**Comment by edenhill** [comment]
We'll want this configurable. Fixed on misc1 branch.

**Comment by edenhill** [comment]
Thanks for your contribution!

**Comment by SSSSeb** [comment]
thank you for librdkafka and kafkacat !

**Comment by SSSSeb** [comment]
actually the MR was incomplete, with slow DNS and/or SSL, you need also 48725ff8d932e417e760d39392846c04b3c704fd

**Comment by edenhill** [comment]
I believe they were all addressed in https://github.com/edenhill/kafkacat/commit/1c53209ba1aa87e4b7c418d53eeea7adc2568db5

**Comment by SSSSeb** [comment]
you still have one at line 2069. bumping this one made a change on my dead-slow setup.

**Comment by edenhill** [comment]
wait_destroyed() is not necessary and should never block, it should actually be removed.

**Pull request closed without merging**
