### PR TITLE
Dockerfile for building static executable

### PR DESCRIPTION
**Pull request by jcaesar**
This is the "Look ma, no hands" kind of pull request. I neither expect nor want it to be accepted. Just saying "Hi, this exists". (And it's been requested before https://github.com/edenhill/kafkacat/issues/159 @jjlin.)

Short notes:
 - I did see https://github.com/edenhill/mklove/issues/20 but that alone won't help: yajl installs its static library to yajl_s and does not make that known to pkg-config. Yay. (Edit: Oh, you seem to be preparing to roll your own yajl anyway…)
 - The dockerfile is based on https://github.com/gentoo/gentoo-docker-images (with some slight modifications for my precarious network situation).
 - It'd be possible to pull this kind of thing outside of a gentoo docker container, but I think that would at least require writing wraps for lz4, zstd, and sasl, and then probably to use meson's cross compilation features. But I'm fuzzy on that part.

### CODE REVIEW

**Comment by jcaesar** [comment]
If SSL/SASL is not required, things are actually doable in an a lot more sane way:
[/jcaesar/kafkacat-static/Dockerfile@1.4.0-0](https://github.com/jcaesar/kafkacat-static/blob/1.4.0-0/Dockerfile).
Maybe not having OpenSSL linked in is the way to go for a static binary anyway…

If you'd like a PR based on this, do tell.

**Comment by jcaesar** [comment]
Oooh, the licensing headache.

SNAFU I guess? https://github.com/edenhill/kafkacat/blob/master/LICENSE#L1

**Comment by solsson** [comment]
A static linux build of kafkacat would indeed be great, for example to add kafkacat to any other docker image using a plain `COPY --from`. What's the relation between this PR and https://github.com/edenhill/librdkafka/pull/2413?

**Comment by jcaesar** [comment]
> for example to add kafkacat to any other docker image
In case you're happy without ssl:
```
FROM liftm/kafkacat:1.4.0 as kafkacat
FROM alpine
COPY --from=kafkacat / /usr
```

> What's the relation between this PR and edenhill/librdkafka#2413?
It's my first time seeing that PR. :( So no idea what the relation is. Guess I could have saved myself the trouble?
The build files used for this are to some extent guesswork since I'm not all that familiar with the underlying libraries. So if @edenhill is putting proper work towards a static build… all the better.

**Comment by solsson** [comment]
@jcaesar Great work with https://hub.docker.com/r/liftm/kafkacat, ticking both boxes: static and automated build. I'll run that until any official approach pops up, and report any issues in https://github.com/jcaesar/kafkacat-static. We use kafkacat for development where we rarely have the need for SSL.

**Comment by jcaesar** [comment]
Guess I'll close this as the situation is good for now and this repo will hopefully eventually have a static build based on https://github.com/edenhill/librdkafka/pull/2413

**Pull request closed without merging**
